## Restricted Boltzmann Machines - Movies Recommendation

Source: https://github.com/echen/restricted-boltzmann-machines 

In [37]:
import numpy as np 

In [38]:
np.__version__

'1.26.4'

In [39]:
# module source https://github.com/echen/restricted-boltzmann-machines 
import rbm

In [40]:
rbm = rbm.RBM(num_visible=6, num_hidden=2)

In [41]:
# dataset creation
'''
Each register (row) represents movies that a person has or has not watched, 
with 0 meaning that they have not watched and 1 meaning that they have watched. 
Each column represents a movie, with a total of 6 movies.
'''
data = np.array([[1, 1, 1, 0, 0, 0],
                 [1, 0, 1, 0, 0, 0],
                 [1, 1, 1, 0, 0, 0],
                 [0, 0, 1, 1, 1, 1],
                 [0, 0, 1, 1, 0, 1],
                 [0, 0, 1, 1, 0, 1]])

In [42]:
data.shape

(6, 6)

In [43]:
movies = ['The Witch', 'The Conjuring', 'The Ring',
           'The Hangover', 'Grown Ups', 'American Pie']

In [44]:
rbm.train(data, max_epochs=3450)

Epoch 0: error is 9.01985701835254
Epoch 1: error is 8.914092533525267
Epoch 2: error is 8.743678649273287
Epoch 3: error is 8.557538949821383
Epoch 4: error is 8.417413475557284
Epoch 5: error is 8.35062128815939
Epoch 6: error is 8.244951985883528
Epoch 7: error is 8.057455759268418
Epoch 8: error is 8.055778808304296
Epoch 9: error is 7.898698977392826
Epoch 10: error is 7.9020194652592695
Epoch 11: error is 7.765631335854133
Epoch 12: error is 7.719414747473275
Epoch 13: error is 7.579163772439892
Epoch 14: error is 7.5077585147420365
Epoch 15: error is 7.582470992692163
Epoch 16: error is 7.594574949713942
Epoch 17: error is 7.4956065203914015
Epoch 18: error is 7.281923041729111
Epoch 19: error is 7.392208871753461
Epoch 20: error is 7.455413241696383
Epoch 21: error is 7.279966605457112
Epoch 22: error is 7.174697232777763
Epoch 23: error is 7.293169414560759
Epoch 24: error is 6.996876514572278
Epoch 25: error is 6.966026736337204
Epoch 26: error is 6.9837631471925
Epoch 27: er

In [45]:
# p.s. first row and first column are random bias values 
# negative value: neuron is not activated. positive values: neuron is activated 
rbm.weights, rbm.weights.shape

(array([[ 2.33493718,  1.88935454,  0.39407057],
        [-0.70504383, -3.20857512,  7.05490772],
        [-0.04656055, -6.1777557 ,  3.05696229],
        [ 4.7350996 ,  3.45223738,  1.82730277],
        [ 0.765908  ,  3.40855963, -7.39849367],
        [-1.2323436 ,  0.52231707, -4.21370298],
        [ 0.77138212,  3.40486296, -7.40217508]]),
 (7, 3))

In [46]:
user1 = np.array([[1, 1, 0, 1, 0, 0]])
user2 = np.array([[0, 0, 0, 1, 1, 0]])

In [47]:
# first position refers to first hidden node and second position refers to second hidden node
# result: likes comedy movies
rbm.run_visible(user1)

array([[0., 0.]])

In [48]:
# result: likes horror movies
rbm.run_visible(user2)

array([[1., 0.]])

In [49]:
hidden_layer = np.array([[1, 0]])
recommendation = rbm.run_hidden(hidden_layer)
recommendation

array([[0., 0., 1., 1., 1., 1.]])

In [50]:
for i in range(len(user1[0])):
    if user2[0, i] == 0 and recommendation[0, i] == 1:
        print(movies[i])

The Ring
American Pie


In [51]:
hidden_layer = np.array([[0, 1]])
recommendation = rbm.run_hidden(hidden_layer)
recommendation

array([[1., 1., 1., 0., 0., 0.]])

In [52]:
for i in range(len(user1[0])):
    if user1[0, i] == 0 and recommendation[0, i] == 1:
        print(movies[i])

The Ring
